# Generated by Django 2.1.2 on 2018-11-04 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('kota', 'Kota'), ('kab', 'Kabupaten')], default='kota', max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('regional_boundary', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('rth_category', models.CharField(max_length=200)),
                ('rth_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rth_area', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
