# Generated by Django 2.1.2 on 2018-11-04 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_cityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geojson', models.FileField(upload_to='maps/city/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson'])])),
            ],
        ),
    ]
