# Generated by Django 2.1.2 on 2018-11-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_citymap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityMap',
            new_name='Map',
        ),
    ]
