# Generated by Django 2.1.2 on 2018-11-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20181104_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprofile',
            name='base_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='map.Map'),
        ),
    ]
