# Generated by Django 2.1.2 on 2018-11-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_cityprofile_base_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprofile',
            name='base_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.Map'),
        ),
    ]
