# Generated by Django 2.1.2 on 2018-11-04 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20181104_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codification', models.CharField(max_length=9, unique=True)),
                ('area_type', models.CharField(choices=[('kota', 'Kota'), ('kab', 'Kabupaten')], default='kota', max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('subdistrict', models.CharField(max_length=200)),
                ('urban_village', models.CharField(max_length=200)),
                ('rth_name', models.CharField(max_length=200)),
                ('rth_address', models.CharField(max_length=200)),
                ('rth_type', models.CharField(max_length=200)),
                ('rth_area', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.FileField(upload_to='maps/icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
                ('base_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.Map')),
            ],
        ),
    ]
