# Generated by Django 2.1.2 on 2018-11-11 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_cityrthprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])])),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='imageslider',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
