# Generated by Django 2.1.2 on 2018-11-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20181111_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.AlterModelOptions(
            name='cityprofile',
            options={'verbose_name': 'Profil Kab/Kota', 'verbose_name_plural': 'Profil Kab/Kota'},
        ),
        migrations.AlterModelOptions(
            name='cityrthprofile',
            options={'verbose_name': 'Profil RTH Kab/Kota', 'verbose_name_plural': 'Profil RTH Kab/Kota'},
        ),
        migrations.AlterModelOptions(
            name='imageslider',
            options={'verbose_name': 'Slide Show', 'verbose_name_plural': 'Daftar Slide Show'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Peta Dasar', 'verbose_name_plural': 'Daftar Peta Dasar'},
        ),
        migrations.AlterModelOptions(
            name='regulation',
            options={'verbose_name': 'Peraturan', 'verbose_name_plural': 'Peraturan'},
        ),
    ]
