# Generated by Django 2.1.2 on 2018-11-12 23:28

import django.core.validators
from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20181112_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to=map.models.Gallery.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])])),
                ('caption', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Galeri Foto',
                'verbose_name_plural': 'Galeri Foto',
            },
        ),
    ]
