# Generated by Django 2.1.2 on 2018-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
