# Generated by Django 2.1.2 on 2018-11-14 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20181114_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='RthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.FileField(upload_to='maps/icon/rth-category', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
            ],
        ),
    ]
