# Generated by Django 2.1.2 on 2018-11-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_rthcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rthcategory',
            options={'verbose_name': 'Jenis RTH', 'verbose_name_plural': 'Jenis RTH'},
        ),
    ]
