# Generated by Django 2.1.2 on 2018-11-14 16:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20181114_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityrthprofile',
            old_name='rth_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cityrthprofile',
            old_name='rth_area',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='codification',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='rth_name',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='rth_type',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='subdistrict',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='urban_village',
        ),
        migrations.AddField(
            model_name='cityrthprofile',
            name='city',
            field=models.CharField(default='Bandung', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityrthprofile',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrthprofile',
            name='planning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cityrthprofile',
            name='rth_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='map.RthCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityrthprofile',
            name='urban_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
