# Generated by Django 2.1.2 on 2018-11-14 18:54

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20181114_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprofile',
            old_name='rth_number',
            new_name='population',
        ),
        migrations.RemoveField(
            model_name='cityprofile',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='cityprofile',
            name='regional_boundary',
        ),
        migrations.RemoveField(
            model_name='cityprofile',
            name='rth_area',
        ),
        migrations.RemoveField(
            model_name='cityprofile',
            name='rth_category',
        ),
        migrations.AddField(
            model_name='cityprofile',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityprofile',
            name='icon',
            field=models.FileField(default='default', upload_to='maps/icon/city-profile', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityprofile',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
