# Generated by Django 2.1.2 on 2018-12-16 14:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_dataprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslider',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
