# Generated by Django 3.0.8 on 2020-09-03 14:06

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20181216_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityprofile',
            options={'verbose_name': 'Profil Kecamatan', 'verbose_name_plural': 'Profil Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='cityrthprofile',
            options={'verbose_name': 'Profil RSU Kecamatan', 'verbose_name_plural': 'Profil PSU Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='rthcategory',
            options={'verbose_name': 'Jenis PSU', 'verbose_name_plural': 'Jenis PSU'},
        ),
        migrations.CreateModel(
            name='DesaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.FileField(upload_to='maps/icon/desa', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
                ('base_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.Map')),
            ],
            options={
                'verbose_name': 'Profil Desa',
                'verbose_name_plural': 'Profil Desa',
            },
        ),
    ]
