# Generated by Django 3.0.8 on 2020-09-05 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20200905_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desaprofile',
            name='geojson',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='maps/desa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson'])]),
        ),
    ]
