# Generated by Django 3.0.8 on 2020-09-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_auto_20200905_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='desaprofile',
            name='color',
            field=models.CharField(default='#abeb34', max_length=200),
        ),
    ]
