# Generated by Django 3.1.1 on 2020-09-06 16:01

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_desaprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesaPsuProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('geojson', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='maps/desa-psu/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson'])])),
                ('color', models.CharField(default='#abeb34', max_length=200)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.FileField(upload_to='maps/icon/desa-psu', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='map.cityrthprofile')),
            ],
            options={
                'verbose_name': 'Profil Desa PSU',
                'verbose_name_plural': 'Profil Desa PSU',
            },
        ),
    ]
