# Generated by Django 3.1.1 on 2020-09-07 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20200907_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('geojson', models.FileField(upload_to='maps/dasar-desa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson'])])),
            ],
            options={
                'verbose_name': 'Peta Dasar Desa',
                'verbose_name_plural': 'Daftar Peta Dasar Desa',
            },
        ),
    ]
