# Generated by Django 3.1.1 on 2020-09-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_mapdesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='geojson',
        ),
        migrations.AddField(
            model_name='desapsuprofile',
            name='base_map',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='map.mapdesa'),
        ),
    ]
