# Generated by Django 3.1.1 on 2020-09-07 15:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_auto_20200907_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='desapsuprofile',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desapsuprofile',
            name='nama_psu',
            field=models.CharField(default='', max_length=200),
        ),
    ]
