# Generated by Django 3.1.1 on 2020-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_auto_20200907_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='desapsuprofile',
            name='urban_area',
            field=models.CharField(default='', max_length=200),
        ),
    ]
