# Generated by Django 3.1.1 on 2020-09-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_desapsuprofile_urban_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='rth_category',
        ),
        migrations.RemoveField(
            model_name='cityrthprofile',
            name='urban_area',
        ),
    ]
