# Generated by Django 3.1.1 on 2020-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20200907_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='desapsuprofile',
            name='planning',
            field=models.CharField(default='', max_length=200),
        ),
    ]
