# Generated by Django 3.1.1 on 2020-09-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_desapsuprofile_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='population',
        ),
    ]
