# Generated by Django 3.1.1 on 2020-09-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_remove_desapsuprofile_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='nama_psu',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='rth_category',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='urban_area',
        ),
    ]
