# Generated by Django 3.1.1 on 2020-09-07 17:14

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0036_auto_20200908_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsuProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_psu', models.CharField(default='', max_length=200)),
                ('urban_area', models.CharField(default='', max_length=200)),
                ('planning', models.CharField(default='', max_length=200)),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.FileField(upload_to='maps/icon/desa-psu', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
                ('desa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='map.desapsuprofile')),
                ('rth_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='map.rthcategory')),
            ],
            options={
                'verbose_name': 'Profil PSU',
                'verbose_name_plural': 'Profil PSU',
            },
        ),
    ]
