# Generated by Django 3.1.1 on 2020-09-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_psuprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='desapsuprofile',
            name='website',
        ),
    ]
