# Generated by Django 3.1.1 on 2020-10-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_auto_20200908_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriProduksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(default='', max_length=200)),
                ('nama_jenis', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Kategory PSU',
                'verbose_name_plural': 'Kategory Psu',
            },
        ),
    ]
