# Generated by Django 3.1.1 on 2020-10-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_psuprofile_kategori_psu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psuprofile',
            name='kategori_psu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.kategoripsu'),
        ),
    ]
