# Generated by Django 3.1.1 on 2020-10-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_auto_20201012_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psuprofile',
            name='kategori_psu',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='map.kategoripsu'),
        ),
    ]
