# Generated by Django 3.1.1 on 2020-10-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_auto_20201012_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdesa',
            name='kecamatan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='map.map'),
        ),
    ]
