# Generated by Django 3.1.1 on 2020-10-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_mapdesa_kecamatan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesaPsuProfile',
        ),
    ]
