# Generated by Django 3.1.1 on 2020-10-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0049_delete_desapsuprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdesa',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mapdesa',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
