# Generated by Django 3.1.1 on 2020-10-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0050_auto_20201013_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdesa',
            name='color',
            field=models.CharField(default='#abeb34', max_length=200),
        ),
    ]
