# Generated by Django 3.1.1 on 2020-10-13 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0051_mapdesa_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.FileField(upload_to='maps/icon/rth-category', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico'])])),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.kategoripsu')),
            ],
            options={
                'verbose_name': 'Jenis PSU',
                'verbose_name_plural': 'Jenis PSU',
            },
        ),
        migrations.RemoveField(
            model_name='psuprofile',
            name='rth_category',
        ),
        migrations.DeleteModel(
            name='RthCategory',
        ),
        migrations.AddField(
            model_name='psuprofile',
            name='jenis_psu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='map.jenispsu'),
        ),
    ]
