# Generated by Django 3.1.1 on 2020-10-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0052_auto_20201013_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Kontak', 'verbose_name_plural': 'Kontak'},
        ),
        migrations.AlterModelOptions(
            name='regulation',
            options={'verbose_name': 'Download', 'verbose_name_plural': 'Download'},
        ),
        migrations.RemoveField(
            model_name='mapdesa',
            name='kecamatan',
        ),
    ]
