# Generated by Django 3.1.1 on 2020-10-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0053_auto_20201020_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoripsu',
            name='nama_jenis',
        ),
    ]
